### ISSUE TITLE
Track issues/fixes amongst various forks and upstream

### ISSUE THREAD

**Issue by grawlinson** [mididings/mididings#4]
There are a few forks of mididings, all with their own separate commit history.

A good place to start would be to track upstream's [issues](https://github.com/dsacre/mididings/issues) and [pull requests](https://github.com/dsacre/mididings/pulls), and pull in fixes when necessary.

### Feature Requests

- [ ] [#12](https://github.com/dsacre/mididings/issues/12) Feature suggestion: make mididings hotplug-capable
- [ ] [#27](https://github.com/dsacre/mididings/issues/27) RPN & NRPN support
- [ ] [#39](https://github.com/dsacre/mididings/issues/39) Using mididings engine from C++

### User Help

- [x] [#8](https://github.com/dsacre/mididings/issues/8) mididings is not listed on PyPI (it is now!)
- [x] [#16](https://github.com/dsacre/mididings/issues/16) send bank and program change on portsplit
- [x] [#18](https://github.com/dsacre/mididings/issues/18) 'git' version not compatible with Boost 1.60
- [x] [#26](https://github.com/dsacre/mididings/issues/26)  Did not run in python 3.6.4 ?
- [x] [#28](https://github.com/dsacre/mididings/issues/28) couldn't find package 'jack'
- [ ] [#29](https://github.com/dsacre/mididings/issues/29) Microtonal tunings
- [ ] [#34](https://github.com/dsacre/mididings/issues/34) Connect to jack-rt ports with their alias
- [x] [#40](https://github.com/dsacre/mididings/issues/40) ubuntu 21.04: /usr/bin/ld: cannot find -lboost_python

### Bug Reports

- [x] [#19](https://github.com/dsacre/mididings/issues/19) current_scene() in init patch returns previous scene number (fixed in [4d915cc](https://github.com/mididings/mididings/commit/4d915cc9cc6eaa40db3645bf88ba5e493bfc25b2))
- [x] [#20](https://github.com/dsacre/mididings/issues/20) Error if scene init_patch is not a list
- [x] [#21](https://github.com/dsacre/mididings/issues/21) NoteOn with zero velocity are discarded (fixed in [533429a](https://github.com/mididings/mididings/commit/533429a68316d56ca49b417e2845c9e28976a511))
- [ ] [#22](https://github.com/dsacre/mididings/issues/22) livedings active scene title highlight lost when another instance receives a scene change
- [ ] [#25](https://github.com/dsacre/mididings/issues/25) Pass() >> Port(n) // Print('xyz') outputs to port 1 as well (jack)
- [x] [#35](https://github.com/dsacre/mididings/issues/35)  async is now a reserved word, beginning in python 3.7 (fixed in [41b2175](https://github.com/mididings/mididings/commit/41b21752d9b85cd958a9a7c634849e3899e4b8bb))
- [x] [#37](https://github.com/dsacre/mididings/issues/37) Fix for SubSceneSwitch with an offset value < 0 and wrap = True
- [x] [#38](https://github.com/dsacre/mididings/issues/38) ProgramFIlter acting as if SuppressPC is running
- [ ] [#43](https://github.com/dsacre/mididings/issues/43) Request for community contributors

## Upstream Pull Requests

All known pull requests have been merged. 🎉

<details><summary>Merged Pull Requests</summary>

### Open

- [x] [#44](https://github.com/dsacre/mididings/issues/44) Adopted to Python 3.11 (already implemented)
- [x] [#32](https://github.com/dsacre/mididings/issues/32) Put duplicated code into aux function (PR merged)
- [x] [#17](https://github.com/dsacre/mididings/issues/17) Add support for get_client_name() and get_client_id() to engine (PR merged)
- [x] [#10](https://github.com/dsacre/mididings/issues/10) Extended setuptools and PyPI support (already implemented)
- [x] [#9](https://github.com/dsacre/mididings/issues/9) Add new example script to show usage of mididing.process_file (PR merged)
- [x] [#7](https://github.com/dsacre/mididings/issues/7) Accept sysex strings in ascii hexadecimal notation with no white-space separation (PR merged)

### Closed

The following PRs are closed, but were not merged.

- [x] [#24](https://github.com/dsacre/mididings/issues/24) Fix harmonizer to work in python3 (fixed in [43c7d68](https://github.com/mididings/mididings/commit/43c7d6804c1b8c1bb1615fa5be4a36b3baebec9a))
</details>

**Comment by grawlinson** [comment]
## Upstream Issues

- [x] [#8](https://github.com/dsacre/mididings/issues/8) mididings is not listed on PyPI (it is now!)
- [ ] [#12](https://github.com/dsacre/mididings/issues/12) Feature suggestion: make mididings hotplug-capable
- [ ] [#16](https://github.com/dsacre/mididings/issues/16) send bank and program change on portsplit
- [ ] [#18](https://github.com/dsacre/mididings/issues/18) 'git' version not compatible with Boost 1.60
- [x] [#19](https://github.com/dsacre/mididings/issues/19) current_scene() in init patch returns previous scene number (fixed in [4d915cc](https://github.com/mididings/mididings/commit/4d915cc9cc6eaa40db3645bf88ba5e493bfc25b2))
- [ ] [#20](https://github.com/dsacre/mididings/issues/20) Error if scene init_patch is not a list
- [x] [#21](https://github.com/dsacre/mididings/issues/21) NoteOn with zero velocity are discarded (fixed in [533429a](https://github.com/mididings/mididings/commit/533429a68316d56ca49b417e2845c9e28976a511))
- [ ] [#22](https://github.com/dsacre/mididings/issues/22) livedings active scene title highlight lost when another instance receives a scene change
- [ ] [#25](https://github.com/dsacre/mididings/issues/25) Pass() >> Port(n) // Print('xyz') outputs to port 1 as well (jack)
- [ ] [#26](https://github.com/dsacre/mididings/issues/26)  Did not run in python 3.6.4 ?
- [ ] [#27](https://github.com/dsacre/mididings/issues/27) RPN & NRPN support
- [ ] [#28](https://github.com/dsacre/mididings/issues/28) couldn't find package 'jack'
- [ ] [#29](https://github.com/dsacre/mididings/issues/29) Microtonal tunings
- [ ] [#34](https://github.com/dsacre/mididings/issues/34) Connect to jack-rt ports with their alias
- [x] [#35](https://github.com/dsacre/mididings/issues/35)  async is now a reserved word, beginning in python 3.7 (fixed in [41b2175](https://github.com/mididings/mididings/commit/41b21752d9b85cd958a9a7c634849e3899e4b8bb))
- [ ] [#37](https://github.com/dsacre/mididings/issues/37) Fix for SubSceneSwitch with an offset value < 0 and wrap = True
- [ ] [#38](https://github.com/dsacre/mididings/issues/38) ProgramFIlter acting as if SuppressPC is running
- [ ] [#39](https://github.com/dsacre/mididings/issues/39) Using mididings engine from C++
- [ ] [#40](https://github.com/dsacre/mididings/issues/40) ubuntu 21.04: /usr/bin/ld: cannot find -lboost_python
- [ ] [#43](https://github.com/dsacre/mididings/issues/43) Request for community contributors

## Upstream Pull Requests

- [x] [#44](https://github.com/dsacre/mididings/issues/44) Adopted to Python 3.11 (already implemented)
- [ ] [#32](https://github.com/dsacre/mididings/issues/32) Put duplicated code into aux function.
- [ ] [#17](https://github.com/dsacre/mididings/issues/17) Add support for get_client_name() and get_client_id() to engine
- [x] [#10](https://github.com/dsacre/mididings/issues/10) Extended setuptools and PyPI support (already implemented)
- [ ] [#9](https://github.com/dsacre/mididings/issues/9) Add new example script to show usage of mididing.process_file
- [ ] [#7](https://github.com/dsacre/mididings/issues/7) Accept sysex strings in ascii hexadecimal notation with no white-space separation

**Comment by LUGKILL2** [comment]
Btw, Mididings, are you contributors looking for a supporter or a maintainer, or just one more team member?

**Comment by stefets** [comment]
Hello @LUGKILL2,

I'm one of the maintainers, but @grawlinson decides. George, I'd like to take this opportunity to let you know that I had a discussion with @romsom, and he'd be very interested in joining the organization.

**Comment by LUGKILL2** [comment]
Any way I can join you guys? (be a contributor) :)

**Comment by LUGKILL2** [comment]
Hi back, by the way I'm just asking if I could participate in your projects
and become a contributor or be a helping hand

**Comment by stefets** [comment]
To keep this issue focused on its original topic, we’ve moved the discussion about new contributor requests here: [link to the discussion](https://github.com/mididings/mididings/discussions/24).

Let’s continue the conversation there so all maintainers can review and provide input.
